# Generated by Django 4.2.2 on 2023-07-03 23:07

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", common.fields.CodeField(max_length=60, verbose_name="Code")),
                ("name", common.fields.NameField(max_length=60, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="spatial.feature")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LivelihoodZone",
            fields=[
                (
                    "zone_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="spatial.zone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("spatial.zone",),
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "zone_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="spatial.zone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("spatial.zone",),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="metadata.currency",
                        verbose_name="Default currency",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.dimension",),
        ),
    ]
