import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    common.models.PrecisionField(decimal_places=16, max_digits=38),
                ),
                (
                    "quantity_usd",
                    common.models.PrecisionField(decimal_places=16, max_digits=38),
                ),
                (
                    "quantity_kcals",
                    common.models.PrecisionField(decimal_places=16, max_digits=38),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", common.models.CodeField(max_length=60, verbose_name="code")),
                ("name", common.models.NameField(max_length=60, verbose_name="name")),
                (
                    "description",
                    common.models.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="description",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DimensionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", common.models.CodeField(max_length=60, verbose_name="code")),
                ("name", common.models.NameField(max_length=60, verbose_name="name")),
                (
                    "description",
                    common.models.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="description",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", common.models.CodeField(max_length=60, verbose_name="code")),
                ("name", common.models.NameField(max_length=60, verbose_name="name")),
            ],
        ),
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LivelihoodStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "quantity",
                    common.models.PrecisionField(decimal_places=16, max_digits=38),
                ),
                (
                    "quantity_usd",
                    common.models.PrecisionField(decimal_places=16, max_digits=38),
                ),
                (
                    "quantity_kcals",
                    common.models.PrecisionField(decimal_places=16, max_digits=38),
                ),
                (
                    "livelihood_strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.livelihoodstrategy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.feature",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.dimension",
                    ),
                ),
            ],
            bases=("activity.dimension",),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.dimension",
                    ),
                ),
            ],
            bases=("activity.dimension",),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.dimension",
                    ),
                ),
            ],
            bases=("activity.dimension",),
        ),
        migrations.CreateModel(
            name="LivelihoodZone",
            fields=[
                (
                    "zone_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.zone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("activity.zone",),
        ),
        migrations.CreateModel(
            name="TranslationType",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.dimension",
                    ),
                ),
            ],
            bases=("activity.dimension",),
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.dimension",
                    ),
                ),
            ],
            bases=("activity.dimension",),
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "zone_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.zone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("activity.zone",),
        ),
        migrations.CreateModel(
            name="WealthGroup",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.dimension",
                    ),
                ),
            ],
            bases=("activity.dimension",),
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField()),
                (
                    "from_dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations_from",
                        to="activity.dimension",
                    ),
                ),
                (
                    "translation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations_of_type",
                        to="activity.dimension",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferItemCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="A single property value, eg, a float, str or list, not a dict of props."
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.dimension",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.transfer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HouseholdCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="A single property value, eg, a float, str or list, not a dict of props."
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.household",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.dimension",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dimension",
            name="dimension_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="activity.dimensiontype"
            ),
        ),
        migrations.CreateModel(
            name="AssetItemCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="A single property value, eg, a float, str or list, not a dict of props."
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="activity.asset"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.dimension",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="activity.household"
            ),
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "unitofmeasure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="activity.unitofmeasure",
                    ),
                ),
            ],
            bases=("activity.unitofmeasure",),
        ),
        migrations.AddField(
            model_name="transfer",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="activity.item"
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="activity.unitofmeasure"
            ),
        ),
        migrations.AddField(
            model_name="livelihoodstrategy",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="activity.activity"
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="village",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="activity.livelihoodzone",
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="wealth_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="activity.wealthgroup"
            ),
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "multiplier",
                    common.models.PrecisionField(decimal_places=16, max_digits=38),
                ),
                (
                    "offset",
                    common.models.PrecisionField(decimal_places=16, max_digits=38),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "from_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="from_conversions",
                        to="activity.dimension",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="to_conversions",
                        to="activity.dimension",
                    ),
                ),
                (
                    "livelihood_zone",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.livelihoodzone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Baseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.country",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="activity.item"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="activity.unitofmeasure"
            ),
        ),
    ]
