version: "3.7"

services:
  app:
    build:
      target: dev
    volumes:
      - ~/.ssh/:/home/ecsmanage/.ssh/
    entrypoint: "ecsmanage"
    command: "inspect"
    environment:
      - CLIENT=${CLIENT:-fnt}
      - APP=${APP:-fdw}
      # defaults to dev in ecsmanage.py when not set in env
      - ENV=${ENV}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
      - ECS_CLUSTER=fnt_ecs
