# Generated by Django 4.2.4 on 2023-10-18 13:54

import common.fields
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0006_unitofmeasure_aliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="HazardCategory",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    common.fields.CodeField(max_length=60, primary_key=True, serialize=False, verbose_name="Code"),
                ),
                ("name", common.fields.NameField(max_length=60, verbose_name="Name")),
                (
                    "description",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The order to display the items in when sorting by this field, if not obvious.",
                        null=True,
                        verbose_name="Ordering",
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        help_text="A list of alternate names for the object.",
                        null=True,
                        verbose_name="aliases",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hazard Category",
                "verbose_name_plural": "Hazard Categories",
            },
        ),
        migrations.CreateModel(
            name="LivelihoodCategory",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    common.fields.CodeField(max_length=60, primary_key=True, serialize=False, verbose_name="Code"),
                ),
                ("name", common.fields.NameField(max_length=60, verbose_name="Name")),
                (
                    "description",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The order to display the items in when sorting by this field, if not obvious.",
                        null=True,
                        verbose_name="Ordering",
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        help_text="A list of alternate names for the object.",
                        null=True,
                        verbose_name="aliases",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livelihood Category",
                "verbose_name_plural": "Livelihood Categories",
            },
        ),
        migrations.CreateModel(
            name="SeasonalActivityType",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    common.fields.CodeField(max_length=60, primary_key=True, serialize=False, verbose_name="Code"),
                ),
                ("name", common.fields.NameField(max_length=60, verbose_name="Name")),
                (
                    "description",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The order to display the items in when sorting by this field, if not obvious.",
                        null=True,
                        verbose_name="Ordering",
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        help_text="A list of alternate names for the object.",
                        null=True,
                        verbose_name="aliases",
                    ),
                ),
                (
                    "activity_category",
                    models.CharField(
                        choices=[
                            ("crop", "Crops"),
                            ("livestock", "Livestock"),
                            ("gardening", "Gardening"),
                            ("fishing", "Fishing"),
                        ],
                        max_length=20,
                        verbose_name="Activity Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seasonal Activity Type",
                "verbose_name_plural": "Seasonal Activity Types",
            },
        ),
        migrations.CreateModel(
            name="WealthCharacteristic",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    common.fields.CodeField(max_length=60, primary_key=True, serialize=False, verbose_name="Code"),
                ),
                ("name", common.fields.NameField(max_length=60, verbose_name="Name")),
                (
                    "description",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The order to display the items in when sorting by this field, if not obvious.",
                        null=True,
                        verbose_name="Ordering",
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        help_text="A list of alternate names for the object.",
                        null=True,
                        verbose_name="aliases",
                    ),
                ),
                (
                    "has_product",
                    models.BooleanField(
                        default=False,
                        help_text="Does a value for this characteristic also require a product?",
                        verbose_name="Has Product?",
                    ),
                ),
                (
                    "has_unit_of_measure",
                    models.BooleanField(
                        default=False,
                        help_text="Does a value for this characteristic also require a unit_of_measure?",
                        verbose_name="Has Unit Of Measure?",
                    ),
                ),
                (
                    "variable_type",
                    models.CharField(
                        choices=[("float", "Numeric"), ("str", "String"), ("bool", "Boolean")],
                        default="str",
                        help_text="Whether the field is numeric, character, boolean, etc.",
                        verbose_name="Variable Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wealth Group Characteristic",
                "verbose_name_plural": "Wealth Group Characteristics",
            },
        ),
        migrations.CreateModel(
            name="WealthGroupCategory",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    common.fields.CodeField(max_length=60, primary_key=True, serialize=False, verbose_name="Code"),
                ),
                ("name", common.fields.NameField(max_length=60, verbose_name="Name")),
                (
                    "description",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The order to display the items in when sorting by this field, if not obvious.",
                        null=True,
                        verbose_name="Ordering",
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        help_text="A list of alternate names for the object.",
                        null=True,
                        verbose_name="aliases",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wealth Group Category",
                "verbose_name_plural": "Wealth Group Categories",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("description", models.TextField(max_length=255, verbose_name="Description")),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("Harvest", "Harvest"),
                            ("Lean", "Lean"),
                            ("Wet", "Wet"),
                            ("Dry", "Dry"),
                            ("Mild", "Mild"),
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                            ("Fall", "Fall"),
                            ("Winter", "Winter"),
                            ("Monsoon", "Monsoon"),
                        ],
                        help_text="Refers to the classification of a specific time of year based on weather patterns, temperature, and other factors",
                        max_length=20,
                        verbose_name="Season Type",
                    ),
                ),
                (
                    "start",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(365),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Start Day",
                    ),
                ),
                (
                    "end",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(365),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="End Day",
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[("Start", "Start"), ("End", "End")],
                        default="End",
                        help_text="Whether a label for a season that contains a single year refers to the start year or the end year for that Season.",
                        max_length=5,
                        verbose_name="Year alignment",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="The order of the Season within the Season Year", verbose_name="Order"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        db_column="country_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", common.fields.NameField(max_length=250, verbose_name="Name")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="An identifier for the Unit, such as the FNID",
                        max_length=25,
                        null=True,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("full_name", common.fields.NameField(max_length=200, unique=True, verbose_name="full name")),
                (
                    "description",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        help_text="A list of alternate names for the Market.",
                        null=True,
                        verbose_name="aliases",
                    ),
                ),
                (
                    "geography",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, geography=True, null=True, srid=4326, verbose_name="geography"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="country_code",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.country",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market",
                "verbose_name_plural": "Markets",
            },
        ),
    ]
