# Generated by Django 4.2.2 on 2023-06-06 12:11

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", common.models.PrecisionField(decimal_places=16, max_digits=38)),
                ("quantity_usd", common.models.PrecisionField(decimal_places=16, max_digits=38)),
                ("quantity_kcals", common.models.PrecisionField(decimal_places=16, max_digits=38)),
            ],
        ),
        migrations.CreateModel(
            name="AssetItemCharacteristic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "value",
                    models.JSONField(
                        help_text="A single property value, eg, a float, str or list, not a dict of props."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("multiplier", common.models.PrecisionField(decimal_places=16, max_digits=38)),
                ("offset", common.models.PrecisionField(decimal_places=16, max_digits=38)),
                ("start", models.DateField()),
                ("end", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", common.models.CodeField(max_length=60, verbose_name="code")),
                ("name", common.models.NameField(max_length=60, verbose_name="name")),
                (
                    "description",
                    common.models.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="description",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DimensionType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", common.models.CodeField(max_length=60, verbose_name="code")),
                ("name", common.models.NameField(max_length=60, verbose_name="name")),
                (
                    "description",
                    common.models.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="description",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Household",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="HouseholdCharacteristic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "value",
                    models.JSONField(
                        help_text="A single property value, eg, a float, str or list, not a dict of props."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="TranslationType",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="WealthGroup",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField()),
                (
                    "from_dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations_from",
                        to="metadata.dimension",
                    ),
                ),
                (
                    "translation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations_of_type",
                        to="metadata.dimension",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferItemCharacteristic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "value",
                    models.JSONField(
                        help_text="A single property value, eg, a float, str or list, not a dict of props."
                    ),
                ),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.dimension")),
            ],
        ),
    ]
