# Generated by Django 4.2.2 on 2023-06-19 20:50

import django.db.models.deletion
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "es_name",
                    common.fields.NameField(
                        blank=True,
                        help_text="Spanish name if different from the English name",
                        max_length=60,
                        verbose_name="Spanish name",
                    ),
                ),
                (
                    "fr_name",
                    common.fields.NameField(
                        blank=True,
                        help_text="French name if different from the English name",
                        max_length=60,
                        verbose_name="French name",
                    ),
                ),
                (
                    "pt_name",
                    common.fields.NameField(
                        blank=True,
                        help_text="Portuguese name if different from the English name",
                        max_length=60,
                        verbose_name="Portuguese name",
                    ),
                ),
                (
                    "ar_name",
                    common.fields.NameField(
                        blank=True,
                        help_text="Arabic name if different from the English name",
                        max_length=60,
                        verbose_name="Arabic name",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("code", common.fields.CodeField(max_length=60, verbose_name="code")),
                (
                    "description",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="description",
                    ),
                ),
                ("default", models.BooleanField(default=False, help_text="The default value in a given sub-list.")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DimensionType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "es_name",
                    common.fields.NameField(
                        blank=True,
                        help_text="Spanish name if different from the English name",
                        max_length=60,
                        verbose_name="Spanish name",
                    ),
                ),
                (
                    "fr_name",
                    common.fields.NameField(
                        blank=True,
                        help_text="French name if different from the English name",
                        max_length=60,
                        verbose_name="French name",
                    ),
                ),
                (
                    "pt_name",
                    common.fields.NameField(
                        blank=True,
                        help_text="Portuguese name if different from the English name",
                        max_length=60,
                        verbose_name="Portuguese name",
                    ),
                ),
                (
                    "ar_name",
                    common.fields.NameField(
                        blank=True,
                        help_text="Arabic name if different from the English name",
                        max_length=60,
                        verbose_name="Arabic name",
                    ),
                ),
                ("code", common.fields.CodeField(max_length=60, verbose_name="code")),
                (
                    "description",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CropType",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Type",
                "verbose_name_plural": "Crop Types",
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="HazardCateogy",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hazard Category",
                "verbose_name_plural": "Hazard Categories",
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="LivelihoodCategory",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livelihood Category",
                "verbose_name_plural": "Livelihood Category",
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="LivestockType",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livestock Type",
                "verbose_name_plural": "Livestock Types",
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="SeasonalActivityCategory",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seasonal Activity Category",
                "verbose_name_plural": "Seasonal Activity Categories",
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="SourceSystem",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="TranslationType",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="WealthCategory",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="WealthGroupCharacteristic",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wealth Group Characteristic",
                "verbose_name_plural": "Wealth Group Characteristics",
            },
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField()),
                (
                    "from_dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations_from",
                        to="metadata.dimension",
                    ),
                ),
                (
                    "translation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations_of_type",
                        to="metadata.dimension",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dimension",
            name="dimension_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.dimensiontype"),
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "unitofmeasure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.unitofmeasure",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("metadata.unitofmeasure",),
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "multiplier",
                    common.fields.PrecisionField(decimal_places=16, max_digits=38, verbose_name="Multiplier"),
                ),
                ("offset", common.fields.PrecisionField(decimal_places=16, max_digits=38, verbose_name="Offset")),
                (
                    "from_date",
                    models.DateField(
                        blank=True,
                        help_text="The first date this conversion is valid.",
                        null=True,
                        verbose_name="From Date",
                    ),
                ),
                (
                    "to_date",
                    models.DateField(
                        blank=True,
                        help_text="The last date this conversion is valid.",
                        null=True,
                        verbose_name="To Date",
                    ),
                ),
                (
                    "from_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Item for which this conversion is valid, if necessary, eg, local kcal %, price.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="metadata.item",
                        verbose_name="From Item",
                    ),
                ),
                (
                    "from_unit_of_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversions_from",
                        to="metadata.unitofmeasure",
                        verbose_name="From Unit of Measure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversion",
                "verbose_name_plural": "Conversions",
            },
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("synonym", common.fields.NameField(max_length=60, verbose_name="name")),
                ("dimension", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.dimension")),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional filter for aliases specific to a source.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="metadata.sourcesystem",
                        verbose_name="Source",
                    ),
                ),
            ],
        ),
    ]
