# Generated by Django 4.2.2 on 2023-06-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spatial", "0001_initial"),
        ("metadata", "0001_initial"),
        ("baseline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferitemcharacteristic",
            name="transfer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="baseline.transfer"),
        ),
        migrations.AddField(
            model_name="householdcharacteristic",
            name="household",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.household"),
        ),
        migrations.AddField(
            model_name="householdcharacteristic",
            name="property",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.dimension"),
        ),
        migrations.AddField(
            model_name="household",
            name="village",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="spatial.livelihoodzone"),
        ),
        migrations.AddField(
            model_name="dimension",
            name="dimension_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.dimensiontype"),
        ),
        migrations.AddField(
            model_name="conversion",
            name="from_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="from_conversions", to="metadata.dimension"
            ),
        ),
        migrations.AddField(
            model_name="conversion",
            name="livelihood_zone",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="spatial.livelihoodzone"
            ),
        ),
        migrations.AddField(
            model_name="conversion",
            name="to_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="to_conversions", to="metadata.dimension"
            ),
        ),
        migrations.AddField(
            model_name="assetitemcharacteristic",
            name="asset",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.asset"),
        ),
        migrations.AddField(
            model_name="assetitemcharacteristic",
            name="property",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.dimension"),
        ),
        migrations.AddField(
            model_name="asset",
            name="household",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.household"),
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "unitofmeasure_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.unitofmeasure",
                    ),
                ),
            ],
            bases=("metadata.unitofmeasure",),
        ),
        migrations.AddField(
            model_name="household",
            name="wealth_group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.wealthgroup"),
        ),
        migrations.AddField(
            model_name="asset",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.item"),
        ),
        migrations.AddField(
            model_name="asset",
            name="unit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.unitofmeasure"),
        ),
    ]
