# Generated by Django 4.2.4 on 2023-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0002_add_ordering_to_dimension"),
    ]

    operations = [
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="has_product",
            field=models.BooleanField(
                default=False,
                help_text="Does a value for this characteristic also require a product?",
                verbose_name="Has Product?",
            ),
        ),
    ]
