# Generated by Django 4.2.4 on 2023-09-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_load_classified_product"),
        ("metadata", "0003_wealthcharacteristic_has_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wealthcharacteristic",
            options={"verbose_name": "Wealth Characteristic", "verbose_name_plural": "Wealth Characteristics"},
        ),
        migrations.AlterField(
            model_name="market",
            name="country",
            field=models.ForeignKey(
                db_column="country_code",
                on_delete=django.db.models.deletion.PROTECT,
                to="common.country",
                verbose_name="Country",
            ),
        ),
    ]
