# Generated by Django 4.2.7 on 2024-02-07 14:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_load_classified_product"),
        ("metadata", "0003_activitylabel"),
    ]

    operations = [
        migrations.CreateModel(
            name="WealthCharacteristicLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "wealth_characteristic_label",
                    common.fields.NameField(max_length=60, unique=True, verbose_name="Wealth Characteristic Label"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_column="product_code",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="wealth_characteristics",
                        to="common.classifiedproduct",
                        verbose_name="Product",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_code",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wealth_characteristics",
                        to="common.unitofmeasure",
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "wealth_characteristic",
                    models.ForeignKey(
                        db_column="wealth_characteristic_code",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="wealth_characteristics",
                        to="metadata.wealthcharacteristic",
                        verbose_name="Wealth Characteristic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wealth Characteristic",
                "verbose_name_plural": "Wealth Characteristics",
            },
        ),
    ]
