# Generated by Django 5.0.2 on 2024-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0004_wealthcharacteristiclabel_activitylabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylabel",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="wealthcharacteristiclabel",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
    ]
