# Generated by Django 5.0.4 on 2024-05-01 22:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_countryclassifiedproductaliases_aliases"),
        ("metadata", "0005_activitylabel_notes_wealthcharacteristiclabel_notes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="activitylabel",
            constraint=models.UniqueConstraint(
                models.F("activity_label"), models.F("activity_type"), name="unique_activity_label_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="wealthcharacteristiclabel",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("wealth_characteristic_label"), name="unique_lower_label"
            ),
        ),
    ]
