# Generated by Django 5.0.4 on 2024-05-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0006_activitylabel_unique_activity_label_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylabel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Complete", "Complete"),
                    ("Discussion", "Under Discussion"),
                    ("Correct BSS", "Correct the BSS"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="wealthcharacteristiclabel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Complete", "Complete"),
                    ("Discussion", "Under Discussion"),
                    ("Correct BSS", "Correct the BSS"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
