# Generated by Django 5.0.2 on 2024-10-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0008_alter_activitylabel_activity_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livelihoodcategory",
            name="color",
            field=models.CharField(
                default="#FFFFFF",
                help_text="Color hex value code for the Livelihood Category.",
                max_length=7,
                verbose_name="Color",
            ),
        ),
    ]
