# Generated by Django 5.1.1 on 2024-11-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0009_livelihoodcategory_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylabel",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("LivelihoodActivity", "Livelihood Activity"),
                    ("OtherCashIncome", "Other Cash Income"),
                    ("WildFoods", "Wild Foods"),
                    ("Seas Cal", "Seas Cal"),
                ],
                default="LivelihoodActivity",
                help_text="The type of Livelihood Activity, either a general Livelihood Activity, or an Other Cash Income activity from the 'Data2' worksheet, or a Wild Foods, Fishing or Hunting activity from the 'Data3' worksheet.",
                max_length=20,
                verbose_name="Activity Type",
            ),
        ),
    ]
