# Generated by Django 5.1.12 on 2025-09-17 16:39

from django.db import migrations, models


def forwards(apps, schema_editor):
    ActivityLabel = apps.get_model("metadata", "ActivityLabel")
    ActivityLabel.objects.filter(status__in=["Complete"]).update(status="Override")


def backwards(apps, schema_editor):
    ActivityLabel = apps.get_model("metadata", "ActivityLabel")
    ActivityLabel.objects.filter(status__in=["Override"]).update(status="Complete")


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0009_livelihoodcategory_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylabel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Regular Expression", "Processed by Regular Expression"),
                    ("Override", "Override automatically recognized metadata"),
                    ("Discussion", "Under Discussion"),
                    ("Correct BSS", "Correct the BSS"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="wealthcharacteristiclabel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Complete", "Complete"),
                    ("Discussion", "Under Discussion"),
                    ("Correct BSS", "Correct the BSS"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
        # Change existing "Complete" ActivityLabel statuses to "Override"
        migrations.RunPython(forwards, backwards),
    ]
