# Generated by Django 5.2.6 on 2025-09-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0010_alter_activitylabel_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylabel",
            name="additional_identifier",
            field=models.CharField(blank=True, max_length=200, verbose_name="Additional Identifier"),
        ),
    ]
