# Generated by Django 5.2.6 on 2025-10-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0011_alter_activitylabel_additional_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylabel",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("LivelihoodActivity", "Livelihood Activity"),
                    ("OtherCashIncome", "Other Cash Income"),
                    ("WildFoods", "Wild Foods, Fishing or Hunting"),
                    ("LivelihoodSummary", "Livelihood Summary"),
                ],
                default="LivelihoodActivity",
                help_text="The type of Livelihood Activity the label is for: either a general Livelihood Activity, or an Other Cash Income activity from the 'Data2' worksheet, or a Wild Foods, Fishing or Hunting activity from the 'Data3' worksheet, or a label from the 'Summary' section of the 'Data' worksheet.",
                max_length=20,
                verbose_name="Activity Type",
            ),
        ),
        migrations.AlterField(
            model_name="activitylabel",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Regular Expression", "Processed by Regular Expression"),
                    ("Override", "Override automatically recognized metadata"),
                    ("Discussion", "Under Discussion"),
                    ("Correct BSS", "Correct the BSS"),
                    ("Ignore", "Ignore this label and associated data in the row"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="activitylabel",
            name="strategy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MilkProduction", "Milk Production"),
                    ("ButterProduction", "Butter Production"),
                    ("MeatProduction", "Meat Production"),
                    ("LivestockSale", "Livestock Sale"),
                    ("CropProduction", "Crop Production"),
                    ("FoodPurchase", "Food Purchase"),
                    ("PaymentInKind", "Payment in Kind"),
                    ("ReliefGiftOther", "Relief, Gift or Other Food"),
                    ("Hunting", "Hunting"),
                    ("Fishing", "Fishing"),
                    ("WildFoodGathering", "Wild Food Gathering"),
                    ("OtherCashIncome", "Other Cash Income"),
                    ("OtherPurchase", "Other Purchase"),
                    ("LivestockProduction", "Livestock Production"),
                ],
                help_text="The type of livelihood strategy, such as crop production, or wild food gathering.",
                max_length=30,
                verbose_name="Strategy Type",
            ),
        ),
    ]
