# Generated by Django 5.2.7 on 2026-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0012_alter_activitylabel_activity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="characteristic_group",
            field=models.CharField(
                blank=True,
                help_text="Optional grouping for characteristics, such as 'Population', 'Income', 'Land', 'Livestock', 'Poultry', 'Other assets'",
                max_length=20,
                null=True,
                verbose_name="Characteristic Group",
            ),
        ),
    ]
