# Generated by Django 5.2.7 on 2026-01-26 06:44

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import common.fields


def forwards(apps, schema_editor):
    WealthCharacteristic = apps.get_model("metadata", "WealthCharacteristic")
    WealthCharacteristic.objects.update(characteristic_group=None)


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0013_wealthcharacteristic_characteristic_group"),
    ]

    operations = [
        migrations.RunPython(
            code=forwards,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="CharacteristicGroup",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    common.fields.CodeField(max_length=60, primary_key=True, serialize=False, verbose_name="Code"),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The order to display the items in when sorting by this field, if not obvious.",
                        null=True,
                        verbose_name="Ordering",
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        help_text="A list of alternate names for the object.",
                        null=True,
                        verbose_name="aliases",
                    ),
                ),
                ("name_en", common.fields.NameField(max_length=60, verbose_name="Name")),
                ("name_fr", common.fields.NameField(blank=True, max_length=60, verbose_name="Name")),
                ("name_es", common.fields.NameField(blank=True, max_length=60, verbose_name="Name")),
                ("name_pt", common.fields.NameField(blank=True, max_length=60, verbose_name="Name")),
                ("name_ar", common.fields.NameField(blank=True, max_length=60, verbose_name="Name")),
                (
                    "description_en",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_fr",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_pt",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_ar",
                    common.fields.DescriptionField(
                        blank=True,
                        help_text="Any extra information or detail that is relevant to the object.",
                        max_length=2000,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Characteristic Group",
                "verbose_name_plural": "Characteristic Groups",
            },
        ),
        migrations.AlterField(
            model_name="wealthcharacteristic",
            name="characteristic_group",
            field=models.ForeignKey(
                blank=True,
                db_column="characteristic_group",  # Add this line
                help_text="Optional grouping for characteristics, such as 'Population', 'Income', 'Land', 'Livestock', 'Other assets'",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="metadata.characteristicgroup",
                verbose_name="Characteristic Group",
            ),
        ),
    ]
