# Generated by Django 5.2.11 on 2026-03-20 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_additionalpermissions"),
        ("metadata", "0015_season_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylabel",
            name="payment_product",
            field=models.ForeignKey(
                blank=True,
                db_column="payment_product_code",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payment_activity_labels",
                to="common.classifiedproduct",
                verbose_name="Payment Product",
            ),
        ),
    ]
