# Generated by Django 5.2.12 on 2026-04-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0016_activitylabel_payment_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylabel",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("LivelihoodActivity", "Livelihood Activity"),
                    ("OtherCashIncome", "Other Cash Income"),
                    ("WildFoods", "Wild Foods, Fishing or Hunting"),
                    ("LivelihoodSummary", "Livelihood Summary"),
                    ("Seas Cal", "Seas Cal"),
                ],
                default="LivelihoodActivity",
                help_text="The type of Livelihood Activity the label is for: either a general Livelihood Activity, or an Other Cash Income activity from the 'Data2' worksheet, or a Wild Foods, Fishing or Hunting activity from the 'Data3' worksheet, or a label from the 'Summary' section of the 'Data' worksheet.",
                max_length=20,
                verbose_name="Activity Type",
            ),
        ),
    ]
