# Generated by Django 5.2.13 on 2026-05-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0016_activitylabel_payment_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="has_product",
            field=models.BooleanField(
                default=False,
                help_text="Does a Seasonal Activity of this type require a product? If True, then aliases may contain a <product> placeholder.",
                verbose_name="Has Product?",
            ),
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="is_key",
            field=models.BooleanField(
                default=False,
                help_text="Are SeasonalActivity instances of this type key seasonal activities?",
                verbose_name="Key Seasonal Activity?",
            ),
        ),
        migrations.AlterField(
            model_name="seasonalactivitytype",
            name="activity_category",
            field=models.CharField(
                choices=[
                    ("season", "Season"),
                    ("crop", "Crops"),
                    ("livestock", "Livestock"),
                    ("fishing", "Fishing"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Activity Category",
            ),
        ),
    ]
