# Generated by Django 5.2.14 on 2026-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0017_seasonalactivitytype_has_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonalactivitytype",
            name="activity_category",
            field=models.CharField(
                choices=[
                    ("climatology", "Climatology"),
                    ("stress_period", "Stress Periods"),
                    ("crop", "Crops"),
                    ("livestock", "Livestock"),
                    ("fishing", "Fishing"),
                    ("other_income", "Employment and Other Income"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Activity Category",
            ),
        ),
    ]
