# Generated by Django 5.2.12 on 2026-05-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0017_other_livestock_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MilkProduction", "Milk Production"),
                    ("ButterProduction", "Butter Production"),
                    ("MeatProduction", "Meat Production"),
                    ("LivestockSale", "Livestock Sale"),
                    ("OtherLivestockProduction", "Other Livestock Production"),
                    ("CropProduction", "Crop Production"),
                    ("FoodPurchase", "Food Purchase"),
                    ("PaymentInKind", "Payment in Kind"),
                    ("ReliefGiftOther", "Relief, Gift or Other Food"),
                    ("Hunting", "Hunting"),
                    ("Fishing", "Fishing"),
                    ("WildFoodGathering", "Wild Food Gathering"),
                    ("OtherCashIncome", "Other Cash Income"),
                    ("OtherPurchase", "Other Purchase"),
                ],
                help_text="The Livelihood Strategy Type that this Season is relevant for.",
                max_length=30,
                null=True,
                verbose_name="Purpose",
            ),
        ),
    ]
