# Generated by Django 5.2.16 on 2026-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0021_alter_wealthcharacteristiclabel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="color",
            field=models.CharField(
                default="#FFFFFF",
                help_text="Color hex value code for the Seasonal Activity Type.",
                max_length=7,
                verbose_name="Color",
            ),
        ),
    ]
