# Generated by Django 5.2.16 on 2026-07-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0022_seasonalactivitytype_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelihoodsystem",
            name="color",
            field=models.CharField(
                default="#9B9D80",
                help_text="Color hex value code for the Livelihood System.",
                max_length=7,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="seasonalactivitytype",
            name="color",
            field=models.CharField(
                default="#9B9D80",
                help_text="Color hex value code for the Seasonal Activity Type.",
                max_length=7,
                verbose_name="Color",
            ),
        ),
    ]
