# Generated by Django 5.2.16 on 2026-09-03 10:48

from django.db import migrations
from django.db.models import F

import common.fields

LANGUAGE_CODES = ("en", "fr", "es", "pt", "ar")

SHORT_NAME_MODELS = (
    "CharacteristicGroup",
    "HazardCategory",
    "LivelihoodSystem",
    "Market",
    "SeasonalActivityType",
    "WealthCharacteristic",
    "WealthGroupCategory",
)


def copy_name_to_short_name(apps, schema_editor):
    # Default short_name to name in every language for existing rows
    for model_name in SHORT_NAME_MODELS:
        model = apps.get_model("metadata", model_name)
        for language_code in LANGUAGE_CODES:
            model.objects.filter(**{f"short_name_{language_code}": ""}).exclude(
                **{f"name_{language_code}": ""}
            ).update(**{f"short_name_{language_code}": F(f"name_{language_code}")})


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0023_alter_livelihoodsystem_color_and_seasonalactivitytype"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=250, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=250, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=250, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=250, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=250, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=60, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.RunPython(copy_name_to_short_name, migrations.RunPython.noop),
    ]
