# Generated by Django 5.2.16 on 2026-09-07 12:06

import textwrap

from django.db import migrations

import common.fields

LANGUAGE_CODES = ("en", "fr", "es", "pt", "ar")

SHORT_NAME_MODELS = (
    "CharacteristicGroup",
    "HazardCategory",
    "LivelihoodSystem",
    "SeasonalActivityType",
    "WealthCharacteristic",
    "WealthGroupCategory",
)

SHORT_NAME_MAX_LENGTH = 40


def _shorten(value):
    value = (value or "").strip()
    if len(value) <= SHORT_NAME_MAX_LENGTH:
        return value
    return (
        textwrap.shorten(value, width=SHORT_NAME_MAX_LENGTH, placeholder="") or value[:SHORT_NAME_MAX_LENGTH].rstrip()
    )


def copy_name_to_short_name(apps, schema_editor):
    # Default short_name to name in every language for existing rows
    for model_name in SHORT_NAME_MODELS:
        model = apps.get_model("metadata", model_name)
        updated = []
        for obj in model.objects.all():
            changed = False
            for language_code in LANGUAGE_CODES:
                if not getattr(obj, f"short_name_{language_code}", ""):
                    setattr(obj, f"short_name_{language_code}", _shorten(getattr(obj, f"name_{language_code}", "")))
                    changed = True
            if changed:
                updated.append(obj)
        if updated:
            model.objects.bulk_update(updated, [f"short_name_{code}" for code in LANGUAGE_CODES])


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0023_alter_livelihoodsystem_color_and_seasonalactivitytype"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characteristicgroup",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hazardcategory",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodsystem",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonalactivitytype",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthcharacteristic",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_ar",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_en",
            field=common.fields.NameField(default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_es",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_fr",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcategory",
            name="short_name_pt",
            field=common.fields.NameField(blank=True, default="", max_length=40, verbose_name="Short Name"),
            preserve_default=False,
        ),
        migrations.RunPython(copy_name_to_short_name, migrations.RunPython.noop),
    ]
