# Generated by Django 4.2.4 on 2023-10-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_load_classified_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitofmeasure",
            name="aliases",
            field=models.JSONField(
                blank=True, help_text="A list of alternate names for the product.", null=True, verbose_name="aliases"
            ),
        ),
    ]
