# Generated by Django 5.1.1 on 2024-11-17 15:34

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("common", "0009_countryclassifiedproductaliases_aliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaProfile",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("expert", models.BooleanField(default=False)),
                ("skip_tour", models.BooleanField(default=False)),
                ("tour_last_viewed", models.DateField(null=True)),
                ("livelihood_explorer_data", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "hea user profile",
                "verbose_name_plural": "hea user profiles",
            },
        ),
    ]
