# Generated by Django 5.2.1 on 2025-09-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalPermissions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "permissions": (("access_dagster_ui", "Can access Dagster user interface"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
