# Generated by Django 4.2.2 on 2023-06-06 12:11

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spatial", "0001_initial"),
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "dimension_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metadata.dimension",
                    ),
                ),
            ],
            bases=("metadata.dimension",),
        ),
        migrations.CreateModel(
            name="LivelihoodStrategy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="baseline.activity")),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("quantity", common.models.PrecisionField(decimal_places=16, max_digits=38)),
                ("quantity_usd", common.models.PrecisionField(decimal_places=16, max_digits=38)),
                ("quantity_kcals", common.models.PrecisionField(decimal_places=16, max_digits=38)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.item")),
                (
                    "livelihood_strategy",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="baseline.livelihoodstrategy"),
                ),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metadata.unitofmeasure")),
            ],
        ),
        migrations.CreateModel(
            name="Baseline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField()),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="spatial.country")),
            ],
        ),
    ]
