# Generated by Django 4.2.4 on 2023-08-15 12:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wealthgroup",
            name="name",
        ),
        migrations.RenameField("CommunityCropProduction", "crop_type", "crop"),
        migrations.RenameField("CommunityCropProduction", "unit_of_land", "unit_of_measure"),
        migrations.RenameField("CommunityLivestock", "livestock_type", "livestock"),
        migrations.AlterField(
            model_name="annualproductionperformance",
            name="annual_performance",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Very Poor"), (2, "Poor"), (3, "Medium"), (4, "Good"), (5, "Very Good")],
                help_text="Rating of the annual production performance from Very Poor (1) to Very Good (5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1, message="Performance rating must be at least 1."),
                    django.core.validators.MaxValueValidator(5, message="Performance rating must be at most 5."),
                ],
                verbose_name="Seasonal Performance",
            ),
        ),
        migrations.AlterField(
            model_name="communitycropproduction",
            name="crop",
            field=models.ForeignKey(
                db_column="crop_code",
                on_delete=django.db.models.deletion.RESTRICT,
                to="common.classifiedproduct",
                verbose_name="Crop Type",
            ),
        ),
        migrations.AlterField(
            model_name="communitycropproduction",
            name="crop_purpose",
            field=models.CharField(
                choices=[("food", "Main Food Crop"), ("cash", "Cash Crop")], max_length=20, verbose_name="Crop purpose"
            ),
        ),
        migrations.AlterField(
            model_name="communitycropproduction",
            name="unit_of_measure",
            field=models.ForeignKey(
                db_column="unit_code",
                on_delete=django.db.models.deletion.RESTRICT,
                to="common.unitofmeasure",
                verbose_name="Unit of Measure",
            ),
        ),
        migrations.AlterField(
            model_name="communitylivestock",
            name="livestock",
            field=models.ForeignKey(
                db_column="livestock_code",
                on_delete=django.db.models.deletion.RESTRICT,
                to="common.classifiedproduct",
                verbose_name="Livestock Type",
            ),
        ),
        migrations.AlterField(
            model_name="livelihoodproductcategory",
            name="product",
            field=models.ForeignKey(
                db_column="product_code",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="staple_foods",
                to="common.classifiedproduct",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="livelihoodstrategy",
            name="currency",
            field=models.ForeignKey(
                db_column="currency_code",
                on_delete=django.db.models.deletion.PROTECT,
                to="common.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="livelihoodstrategy",
            name="product",
            field=models.ForeignKey(
                db_column="product_code",
                help_text="Product, e.g. full fat milk",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livelihood_strategies",
                to="common.classifiedproduct",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="marketprice",
            name="currency",
            field=models.ForeignKey(
                db_column="currency_code",
                on_delete=django.db.models.deletion.RESTRICT,
                to="common.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="marketprice",
            name="product",
            field=models.ForeignKey(
                db_column="product_code",
                help_text="Product, e.g. full fat milk",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="market_prices",
                to="common.classifiedproduct",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="marketprice",
            name="unit_of_measure",
            field=models.ForeignKey(
                db_column="unit_code",
                on_delete=django.db.models.deletion.RESTRICT,
                to="common.unitofmeasure",
                verbose_name="Unit of Measure",
            ),
        ),
        migrations.AlterField(
            model_name="milkproduction",
            name="type_of_milk_sold_or_other_uses",
            field=models.CharField(
                choices=[("skim", "Skim"), ("whole", "whole")], verbose_name="Skim or whole milk sold or used"
            ),
        ),
        migrations.AlterField(
            model_name="seasonalactivity",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product_code",
                help_text="Product, e.g. full fat milk",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="baseline_seasonal_activities",
                to="common.classifiedproduct",
                verbose_name="Product",
            ),
        ),
        migrations.CreateModel(
            name="BaselineLivelihoodActivity",
            fields=[],
            options={
                "verbose_name": "Baseline Livelihood Activity",
                "verbose_name_plural": "Baseline Livelihood Activities",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("baseline.livelihoodactivity",),
        ),
        migrations.CreateModel(
            name="ResponseLivelihoodActivity",
            fields=[],
            options={
                "verbose_name": "Response Livelihood Activity",
                "verbose_name_plural": "Response Livelihood Activities",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("baseline.livelihoodactivity",),
        ),
    ]
