# Generated by Django 4.2.4 on 2023-11-08 17:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
        ("baseline", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel("AnnualProductionPerformance", "SeasonalProductionPerformance"),
        migrations.AlterModelOptions(
            name="seasonalproductionperformance",
            options={
                "verbose_name": "Seasonal Production Performance",
                "verbose_name_plural": "Seasonal Production Performance",
            },
        ),
        migrations.RenameField(
            model_name="seasonalproductionperformance",
            old_name="annual_performance",
            new_name="seasonal_performance",
        ),
        migrations.AlterField(
            model_name="seasonalproductionperformance",
            name="seasonal_performance",
            field=models.SmallIntegerField(
                choices=[(1, "Very Poor"), (2, "Poor"), (3, "Medium"), (4, "Good"), (5, "Very Good")],
                help_text="Rating of the seasonal production performance from Very Poor (1) to Very Good (5)",
                validators=[
                    django.core.validators.MinValueValidator(1, message="Performance rating must be at least 1."),
                    django.core.validators.MaxValueValidator(5, message="Performance rating must be at most 5."),
                ],
                verbose_name="Seasonal Performance",
            ),
        ),
        # Note that this migration will fail if there is any existing data in the database,
        # because there won't be a Season with id=9999. This is expected - we anticipate
        # that this migration will always run before any BSS are loaded into the database.
        migrations.AddField(
            model_name="seasonalproductionperformance",
            name="season",
            field=models.ForeignKey(
                default=9999, on_delete=django.db.models.deletion.PROTECT, to="metadata.season", verbose_name="Season"
            ),
            preserve_default=False,
        ),
    ]
