# Generated by Django 4.2.4 on 2023-11-30 14:19

from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0002_seasonalproductionperformance_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="community",
            name="baseline_community_livelihood_zone_baseline_full_name_uniq",
        ),
        migrations.RenameField(
            model_name="community",
            old_name="full_name",
            new_name="full_name_en",
        ),
        migrations.RenameField(
            model_name="community",
            old_name="name",
            new_name="name_en",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="hazard",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="livelihoodzone",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="livelihoodzone",
            old_name="name",
            new_name="name_en",
        ),
        migrations.RenameField(
            model_name="livelihoodzonebaseline",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="livelihoodzonebaseline",
            old_name="name",
            new_name="name_en",
        ),
        migrations.RenameField(
            model_name="marketprice",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="sourceorganization",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="sourceorganization",
            old_name="full_name",
            new_name="full_name_en",
        ),
        migrations.RenameField(
            model_name="sourceorganization",
            old_name="name",
            new_name="name_en",
        ),
        migrations.AddField(
            model_name="community",
            name="full_name_ar",
            field=common.fields.NameField(
                default="",
                help_text="The full name the Community, including the parent administrative units.",
                max_length=200,
                verbose_name="Full Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="full_name_es",
            field=common.fields.NameField(
                default="",
                help_text="The full name the Community, including the parent administrative units.",
                max_length=200,
                verbose_name="Full Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="full_name_fr",
            field=common.fields.NameField(
                default="",
                help_text="The full name the Community, including the parent administrative units.",
                max_length=200,
                verbose_name="Full Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="full_name_pt",
            field=common.fields.NameField(
                default="",
                help_text="The full name the Community, including the parent administrative units.",
                max_length=200,
                verbose_name="Full Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="name_ar",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="name_es",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="name_fr",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="community",
            name="name_pt",
            field=common.fields.NameField(default="", max_length=60, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="description_ar",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=255,
                verbose_name="Description of Event(s) and/or Response(s)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description_es",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=255,
                verbose_name="Description of Event(s) and/or Response(s)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description_fr",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=255,
                verbose_name="Description of Event(s) and/or Response(s)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description_pt",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=255,
                verbose_name="Description of Event(s) and/or Response(s)",
            ),
        ),
        migrations.AddField(
            model_name="hazard",
            name="description_ar",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=255,
                verbose_name="Description of Event(s) and/or Response(s)",
            ),
        ),
        migrations.AddField(
            model_name="hazard",
            name="description_es",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=255,
                verbose_name="Description of Event(s) and/or Response(s)",
            ),
        ),
        migrations.AddField(
            model_name="hazard",
            name="description_fr",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=255,
                verbose_name="Description of Event(s) and/or Response(s)",
            ),
        ),
        migrations.AddField(
            model_name="hazard",
            name="description_pt",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=255,
                verbose_name="Description of Event(s) and/or Response(s)",
            ),
        ),
        migrations.AddField(
            model_name="livelihoodzone",
            name="description_ar",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="livelihoodzone",
            name="description_es",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="livelihoodzone",
            name="description_fr",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="livelihoodzone",
            name="description_pt",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="livelihoodzone",
            name="name_ar",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodzone",
            name="name_es",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodzone",
            name="name_fr",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodzone",
            name="name_pt",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="description_ar",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="description_es",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="description_fr",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="description_pt",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="name_ar",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="name_es",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="name_fr",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="name_pt",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketprice",
            name="description_ar",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=100,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="marketprice",
            name="description_es",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=100,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="marketprice",
            name="description_fr",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=100,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="marketprice",
            name="description_pt",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=100,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="description_ar",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="description_es",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="description_fr",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="description_pt",
            field=common.fields.DescriptionField(
                blank=True,
                help_text="Any extra information or detail that is relevant to the object.",
                max_length=2000,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="full_name_ar",
            field=common.fields.NameField(default="", max_length=300, unique=True, verbose_name="full name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="full_name_es",
            field=common.fields.NameField(default="", max_length=300, unique=True, verbose_name="full name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="full_name_fr",
            field=common.fields.NameField(default="", max_length=300, unique=True, verbose_name="full name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="full_name_pt",
            field=common.fields.NameField(default="", max_length=300, unique=True, verbose_name="full name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="name_ar",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="name_es",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="name_fr",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourceorganization",
            name="name_pt",
            field=common.fields.NameField(default="", max_length=200, unique=True, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="community",
            constraint=models.UniqueConstraint(
                fields=("livelihood_zone_baseline", "full_name_en"),
                name="baseline_community_livelihood_zone_baseline_full_name_uniq",
            ),
        ),
    ]
