# Generated by Django 4.2.4 on 2023-08-22 16:14

from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0002_rename_fields_and_db_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="A short identifier for the Community",
                max_length=25,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="full_name",
            field=common.fields.NameField(
                default="",
                help_text="The full name the Community, including the parent administrative units.",
                max_length=200,
                verbose_name="Full Name",
            ),
            preserve_default=False,
        ),
    ]
