# Generated by Django 4.2.4 on 2023-08-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0003_add_community_full_name_and_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="wealthgroupcharacteristicvalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("community_interview", "Community Interview (Form 3)"),
                    ("wealth_group_interview", "Wealth Group Interview (Form 4)"),
                    ("baseline_summary", "Baseline Summary"),
                ],
                db_index=True,
                default="wealth_group",
                help_text="The source of this Wealth Group Characteristic Value, such as a Community Interview (Form 3), or the Baseline Summary",  # NOQA: E501
                max_length=30,
                verbose_name="Characteristic Source",
            ),
            preserve_default=False,
        ),
    ]
