# Generated by Django 4.2.4 on 2023-09-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0004_add_wealth_group_characteristic_value_source_and_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="interview_number",
        ),
        migrations.RemoveField(
            model_name="community",
            name="interviewers",
        ),
    ]
