# Generated by Django 4.2.4 on 2023-08-30 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0004_correct_expandibility_percentage_spelling"),
    ]

    operations = [
        migrations.AddField(
            model_name="wealthgroupcharacteristicvalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("community_interview", "Community Interview (Form 3)"),
                    ("wealth_group_interview", "Wealth Group Interview (Form 4)"),
                    ("baseline_summary", "Baseline Summary"),
                ],
                db_index=True,
                default="wealth_group",
                help_text="The source of this Wealth Group Characteristic Value, such as a Community Interview (Form 3), or the Baseline Summary",  # NOQA: E501
                max_length=30,
                verbose_name="Characteristic Source",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wealthgroupcharacteristicvalue",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product_code",
                help_text="Product, e.g. Cattle",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wealth_group_characteristic_values",
                to="common.classifiedproduct",
                verbose_name="Product",
            ),
        ),
        migrations.AddConstraint(
            model_name="wealthgroupcharacteristicvalue",
            constraint=models.UniqueConstraint(
                fields=("wealth_group", "wealth_characteristic", "source", "product"),
                name="baseline_wealthgroupcharacteristicvalue_group_characteristic_source_product_uniq",
            ),
        ),
    ]
