# Generated by Django 4.2.7 on 2024-01-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0004_add_translation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonalactivity",
            name="additional_identifier",
            field=models.CharField(
                blank=True,
                help_text="Additional text identifying the seasonal activity",
                max_length=60,
                verbose_name="Additional Identifier",
            ),
        ),
    ]
