# Generated by Django 4.2.7 on 2024-01-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0005_seasonalactivity_additional_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="livelihoodzone",
            name="alternate_code",
            field=models.CharField(
                blank=True,
                help_text="Alternate identifier for the Livelihood Zone, typically a meaningful code based on the name of the Zone.",  # NOQA: E501
                max_length=25,
                verbose_name="alternate code",
            ),
        ),
    ]
