# Generated by Django 4.2.4 on 2023-09-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0006_community_baseline_community_livelihood_zone_baseline_full_name_uniq_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="interview_number",
        ),
        migrations.RemoveField(
            model_name="community",
            name="interviewers",
        ),
    ]
