# Generated by Django 4.2.7 on 2024-02-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0007_alter_livelihoodstrategy_unit_of_measure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livelihoodactivity",
            name="extra",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional attributes from the BSS for this Livelihood Activity",
                null=True,
                verbose_name="Extra attributes",
            ),
        ),
    ]
