# Generated by Django 5.0.2 on 2024-03-15 07:33

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0009_hunting_alter_livelihoodactivity_strategy_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LivelihoodZoneBaselineCorrection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "worksheet_name",
                    models.CharField(
                        choices=[("wb", "Wb"), ("data", "Data"), ("data2", "Data2"), ("data3", "Data3")],
                        max_length=20,
                        verbose_name="Worksheet name",
                    ),
                ),
                ("cell_range", models.CharField(max_length=10, verbose_name="Cell range")),
                ("previous_value", models.CharField(max_length=255, verbose_name="Previous value before correction")),
                ("value", models.CharField(max_length=255, verbose_name="Corrected value")),
                ("correction_date", models.DateTimeField(auto_now_add=True, verbose_name="Correction date")),
                (
                    "comment",
                    models.TextField(
                        help_text="Required comment about the correction suggested",
                        max_length=255,
                        verbose_name="Correction comments",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Correction author",
                    ),
                ),
                (
                    "livelihood_zone_baseline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="baseline.livelihoodzonebaseline",
                        verbose_name="Livelihood Zone Baseline",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
