# Generated by Django 5.0.2 on 2024-04-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0012_livelihoodzonebaselinecorrection"),
        ("common", "0009_countryclassifiedproductaliases_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                db_column="currency_code",
                help_text="Default currency for income or expenditure from Livelihood Activities within this Baseline.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.currency",
                verbose_name="Currency",
            ),
        ),
    ]
