# Generated by Django 5.0.2 on 2024-04-22 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0013_alter_livelihoodzonebaseline_name_en_and_more"),
        ("common", "0009_countryclassifiedproductaliases_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="currency",
            field=models.ForeignKey(
                db_column="currency_code",
                default="USD",
                help_text="Default currency for income or expenditure from Livelihood Activities within this Baseline.",
                on_delete=django.db.models.deletion.PROTECT,
                to="common.currency",
                verbose_name="Currency",
            ),
        ),
    ]
