# Generated by Django 5.0.2 on 2024-05-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0015_alter_livelihoodzonebaselinecorrection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelihoodstrategy",
            name="additional_identifier",
            field=models.CharField(
                blank=True,
                help_text="Additional text identifying the livelihood strategy",
                max_length=200,
                verbose_name="Additional Identifer",
            ),
        ),
        migrations.AlterField(
            model_name="foodpurchase",
            name="months_per_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of months in a year that the product is purchased",
                null=True,
                verbose_name="Months per year",
            ),
        ),
        migrations.AlterField(
            model_name="foodpurchase",
            name="times_per_month",
            field=models.FloatField(blank=True, null=True, verbose_name="Purchases per month"),
        ),
        migrations.AlterField(
            model_name="paymentinkind",
            name="times_per_month",
            field=models.FloatField(blank=True, null=True, verbose_name="Labor per month"),
        ),
    ]
