# Generated by Django 5.1.1 on 2024-10-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0016_alter_livelihoodstrategy_additional_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelihoodzonebaselinecorrection",
            name="worksheet_name",
            field=models.CharField(
                choices=[
                    ("WB", "WB"),
                    ("Data", "Data"),
                    ("Data2", "Data2"),
                    ("Data3", "Data3"),
                    ("Timeline", "Timeline"),
                    ("Seas Cal", "Seas Cal"),
                ],
                max_length=20,
                verbose_name="Worksheet name",
            ),
        ),
    ]
