# Generated by Django 5.1.1 on 2024-11-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0018_alter_livelihoodactivity_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodpurchase",
            name="times_per_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of times in a year that the purchase is made",
                null=True,
                verbose_name="Times per year",
            ),
        ),
        migrations.AlterField(
            model_name="foodpurchase",
            name="unit_multiple",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Multiple of the unit of measure in a single purchase",
                null=True,
                verbose_name="Unit Multiple",
            ),
        ),
        migrations.AlterField(
            model_name="othercashincome",
            name="times_per_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of times in a year that the income is received",
                null=True,
                verbose_name="Times per year",
            ),
        ),
        migrations.AlterField(
            model_name="otherpurchase",
            name="times_per_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of times in a year that the product is purchased",
                null=True,
                verbose_name="Times per year",
            ),
        ),
        migrations.AlterField(
            model_name="paymentinkind",
            name="months_per_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of months in a year that the labor is performed",
                null=True,
                verbose_name="Months per year",
            ),
        ),
        migrations.AlterField(
            model_name="paymentinkind",
            name="people_per_household",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of household members who perform the labor",
                null=True,
                verbose_name="People per household",
            ),
        ),
        migrations.AlterField(
            model_name="paymentinkind",
            name="times_per_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of times in a year that the labor is performed",
                null=True,
                verbose_name="Times per year",
            ),
        ),
        migrations.AlterField(
            model_name="reliefgiftother",
            name="times_per_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of times in a year that the item is received",
                null=True,
                verbose_name="Times per year",
            ),
        ),
        migrations.AlterField(
            model_name="reliefgiftother",
            name="unit_multiple",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Multiple of the unit of measure received each time",
                null=True,
                verbose_name="Unit Multiple",
            ),
        ),
    ]
