# Generated by Django 5.2.7 on 2025-11-05 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0019_alter_foodpurchase_times_per_year_and_more"),
        ("metadata", "0012_alter_activitylabel_activity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wealthgroup",
            name="wealth_group_category",
            field=models.ForeignKey(
                db_column="wealth_group_category_code",
                help_text="Wealth Group Category, e.g. Poor or Better Off",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wealth_groups",
                to="metadata.wealthgroupcategory",
                verbose_name="Wealth Group Category",
            ),
        ),
    ]
