# Generated by Django 5.2.7 on 2025-11-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0020_alter_wealthgroup_wealth_group_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livelihoodproductcategory",
            name="livelihood_zone_baseline",
        ),
        migrations.RemoveField(
            model_name="livelihoodproductcategory",
            name="product",
        ),
        migrations.AddField(
            model_name="livelihoodproductcategory",
            name="baseline_livelihood_activity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="baseline.baselinelivelihoodactivity",
                verbose_name="Baseline Livelihood Activity",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livelihoodproductcategory",
            name="percentage_allocation_to_basket",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The percentage of expenditure or kcals from the Livelihood Activity that is allocated to this Basket. The remainder is implicitly part of the 'Other' basket",
                null=True,
                verbose_name="Percentage allocation to basket",
            ),
        ),
    ]
