# Generated by Django 5.2.7 on 2025-12-29 07:04

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0021_remove_livelihoodproductcategory_livelihood_zone_baseline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wealthgroup",
            name="average_household_size",
            field=models.FloatField(
                blank=True,
                help_text="Average number of people per household in this Wealth Group",
                null=True,
                validators=[common.models.validate_positive],
                verbose_name="Average household size",
            ),
        ),
    ]
