# Generated by Django 5.2.7 on 2025-12-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0021_remove_livelihoodproductcategory_livelihood_zone_baseline_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wealthgroup",
            options={
                "ordering": [
                    "livelihood_zone_baseline__livelihood_zone__code",
                    "livelihood_zone_baseline__reference_year_end_date",
                    "wealth_group_category__ordering",
                    "community__name",
                ],
                "verbose_name": "Wealth Group",
                "verbose_name_plural": "Wealth Groups",
            },
        ),
    ]
