# Generated by Django 5.2.7 on 2025-12-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0022_alter_wealthgroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="household_labor_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("men", "Mainly Men"),
                    ("women", "Mainly Women"),
                    ("children", "Mainly Children"),
                    ("boys", "Mainly Boys"),
                    ("girls", "Mainly Girls"),
                    ("adults", "Mainly Adults"),
                    ("all", "All Together"),
                ],
                max_length=10,
                verbose_name="Activity done by",
            ),
        ),
    ]
