# Generated by Django 5.2.9 on 2026-01-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0023_alter_wealthgroup_average_household_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineWealthGroupCharacteristicValue",
            fields=[],
            options={
                "verbose_name": "Baseline Wealth Group Characteristic Value",
                "verbose_name_plural": "Baseline Wealth Group Characteristic Values",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("baseline.wealthgroupcharacteristicvalue",),
        ),
        migrations.CreateModel(
            name="CommunityWealthGroupCharacteristicValue",
            fields=[],
            options={
                "verbose_name": "Community Wealth Group Characteristic Value",
                "verbose_name_plural": "Community Wealth Group Characteristic Values",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("baseline.wealthgroupcharacteristicvalue",),
        ),
    ]
