# Generated by Django 5.2.10 on 2026-02-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0024_baselinewealthgroupcharacteristicvalue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milkproduction",
            name="milking_animals",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Number of milking animals"),
        ),
    ]
