# Generated by Django 5.2.11 on 2026-03-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0026_add_boys_girls_adults_to_household_labor_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonalactivity",
            name="livelihood_zone_baseline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baseline_seasonal_activities",
                to="baseline.livelihoodzonebaseline",
                verbose_name="Livelihood Zone Baseline",
            ),
        ),
    ]
