# Generated by Django 5.2.11 on 2026-03-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0027_alter_seasonalactivity_livelihood_zone_baseline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_consumed",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Consumed"),
        ),
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_other_uses",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Other Uses"),
        ),
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_produced",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Produced"),
        ),
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_purchased",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Purchased"),
        ),
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_sold",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Sold/Exchanged"),
        ),
    ]
