# Generated by Django 5.2.11 on 2026-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0027_alter_seasonalactivity_livelihood_zone_baseline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meatproduction",
            name="animals_slaughtered",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Number of animals slaughtered"
            ),
        ),
        migrations.AlterField(
            model_name="meatproduction",
            name="carcass_weight",
            field=models.FloatField(blank=True, null=True, verbose_name="Carcass weight per animal"),
        ),
    ]
