# Generated by Django 5.2.11 on 2026-03-19 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0027_alter_seasonalactivity_livelihood_zone_baseline"),
        ("common", "0011_additionalpermissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinkind",
            name="payment_product",
            field=models.ForeignKey(
                blank=True,
                db_column="payment_product_code",
                help_text="Product provided as payment, typically a staple food item in exchange for labor",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_in_kind",
                to="common.classifiedproduct",
                verbose_name="Payment Product",
            ),
        ),
    ]
