# Generated by Django 5.2.12 on 2026-04-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0029_alter_meatproduction_animals_slaughtered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodpurchase",
            name="unit_multiple",
            field=models.FloatField(
                blank=True,
                help_text="Multiple of the unit of measure in a single purchase",
                null=True,
                verbose_name="Unit Multiple",
            ),
        ),
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_consumed",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Consumed"),
        ),
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_other_uses",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Other Uses"),
        ),
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_produced",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Produced"),
        ),
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_purchased",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Purchased"),
        ),
        migrations.AlterField(
            model_name="livelihoodactivity",
            name="quantity_sold",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity Sold/Exchanged"),
        ),
        migrations.AlterField(
            model_name="milkproduction",
            name="quantity_butter_production",
            field=models.FloatField(blank=True, null=True, verbose_name="Quantity used for Butter Production"),
        ),
        migrations.AlterField(
            model_name="otherpurchase",
            name="unit_multiple",
            field=models.FloatField(
                blank=True,
                help_text="Multiple of the unit of measure in a single purchase",
                null=True,
                verbose_name="Unit Multiple",
            ),
        ),
        migrations.AlterField(
            model_name="reliefgiftother",
            name="unit_multiple",
            field=models.FloatField(
                blank=True,
                help_text="Multiple of the unit of measure received each time",
                null=True,
                verbose_name="Unit Multiple",
            ),
        ),
    ]
