# Generated by Django 5.2.12 on 2026-04-17 14:36

import django.db.models.functions.text
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0030_alter_foodpurchase_unit_multiple_and_more"),
        ("common", "0011_additionalpermissions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="community",
            name="baseline_community_livelihood_zone_baseline_full_name_uniq",
        ),
        migrations.AlterField(
            model_name="livelihoodzone",
            name="name_en",
            field=common.fields.NameField(max_length=200, verbose_name="Name"),
        ),
        migrations.AddConstraint(
            model_name="community",
            constraint=models.UniqueConstraint(
                models.F("livelihood_zone_baseline"),
                django.db.models.functions.text.Lower("full_name"),
                name="baseline_community_livelihood_zone_baseline_full_name_lower_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"), name="baseline_livelihoodzone_code_lower_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzone",
            constraint=models.UniqueConstraint(
                models.F("country"),
                django.db.models.functions.text.Lower("alternate_code"),
                condition=models.Q(("alternate_code__isnull", False), models.Q(("alternate_code", ""), _negated=True)),
                name="baseline_livelihoodzone_country_alternate_code_lower_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_en"), name="baseline_livelihoodzone_name_en_lower_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_ar"),
                condition=models.Q(("name_ar", ""), _negated=True),
                name="baseline_livelihoodzone_name_ar_lower_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_es"),
                condition=models.Q(("name_es", ""), _negated=True),
                name="baseline_livelihoodzone_name_es_lower_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_fr"),
                condition=models.Q(("name_fr", ""), _negated=True),
                name="baseline_livelihoodzone_name_fr_lower_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_pt"),
                condition=models.Q(("name_pt", ""), _negated=True),
                name="baseline_livelihoodzone_name_pt_lower_uniq",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="livelihoodzonebaseline",
            name="baseline_livelihoodzonebaseline_name_en_reference_year_end_date_uniq",
        ),
        migrations.AddConstraint(
            model_name="livelihoodzonebaseline",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_en"),
                models.F("reference_year_end_date"),
                name="baseline_livelihoodzonebaseline_name_en_lower_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzonebaseline",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_ar"),
                models.F("reference_year_end_date"),
                condition=models.Q(("name_ar", ""), _negated=True),
                name="baseline_livelihoodzonebaseline_name_ar_lower_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzonebaseline",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_es"),
                models.F("reference_year_end_date"),
                condition=models.Q(("name_es", ""), _negated=True),
                name="baseline_livelihoodzonebaseline_name_es_lower_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzonebaseline",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_fr"),
                models.F("reference_year_end_date"),
                condition=models.Q(("name_fr", ""), _negated=True),
                name="baseline_livelihoodzonebaseline_name_fr_lower_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="livelihoodzonebaseline",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name_pt"),
                models.F("reference_year_end_date"),
                condition=models.Q(("name_pt", ""), _negated=True),
                name="baseline_livelihoodzonebaseline_name_pt_lower_uniq",
            ),
        ),
    ]
