# Generated by Django 5.2.12 on 2026-04-19 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0031_case_insensitive_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wealthgroup",
            name="percentage_of_households",
            field=models.FloatField(
                blank=True,
                help_text="Percentage of households in the Community or Livelihood Zone that are in this Wealth Group",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Percentage of households",
            ),
        ),
        migrations.AlterField(
            model_name="expandabilityfactor",
            name="percentage_consumed",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity Consumed",
            ),
        ),
        migrations.AlterField(
            model_name="expandabilityfactor",
            name="percentage_expenditure",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Expenditure",
            ),
        ),
        migrations.AlterField(
            model_name="expandabilityfactor",
            name="percentage_income",
            field=models.FloatField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Income"
            ),
        ),
        migrations.AlterField(
            model_name="expandabilityfactor",
            name="percentage_other_uses",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity Other Uses",
            ),
        ),
        migrations.AlterField(
            model_name="expandabilityfactor",
            name="percentage_produced",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity Produced",
            ),
        ),
        migrations.AlterField(
            model_name="expandabilityfactor",
            name="percentage_sold",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity Sold/Exchanged",
            ),
        ),
        migrations.AlterField(
            model_name="livelihoodproductcategory",
            name="basket",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Main Staple"),
                    (2, "Other food survival"),
                    (3, "Non-food survival"),
                    (4, "Livelihoods Protection"),
                ],
                verbose_name="Product Basket",
            ),
        ),
        migrations.AlterField(
            model_name="livelihoodproductcategory",
            name="percentage_allocation_to_basket",
            field=models.FloatField(
                default=0.0,
                help_text="The percentage of expenditure or kcals from the Livelihood Activity that is allocated to this Basket. The remainder is implicitly part of the 'Other' basket",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Percentage allocation to basket",
            ),
            preserve_default=False,
        ),
    ]
