# Generated by Django 5.2.11 on 2026-05-03 14:30

from django.db import migrations, models


def populate_annual_kcals_cost(apps, schema_editor):
    schema_editor.execute("""
        UPDATE baseline_livelihoodzonebaseline
        SET _annual_kcals_cost = get_annual_kcals_cost(id, 'P')
        """)


def clear_annual_kcals_cost(apps, schema_editor):
    schema_editor.execute("""
        UPDATE baseline_livelihoodzonebaseline
        SET _annual_kcals_cost = NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0033_add_annual_kcals_cost_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="livelihoodzonebaseline",
            name="_annual_kcals_cost",
            field=models.FloatField(
                blank=True,
                help_text="Annual cost per person of 100% of recommended kcals in the baseline currency.",
                null=True,
                verbose_name="Annual kcals cost",
            ),
        ),
        migrations.RunPython(populate_annual_kcals_cost, clear_annual_kcals_cost),
    ]
