# Generated by Django 5.2.12 on 2026-04-17 02:28

from django.db import migrations, models

POPULATE_SORT_KEY = """
UPDATE baseline_livelihoodactivity la
  SET sort_key = concat_ws('~',
      lzb.livelihood_zone_code,
      lzb.reference_year_end_date::text,
      lpad(coalesce(wgc.ordering::text, '0'), 5, '0'),
      la.strategy_type,
      coalesce(s.name_en, ''),
      coalesce(ls.product_code, ''),
      left(ls.additional_identifier, 50),
      left(coalesce(c.full_name, ''), 50),
      la.scenario
  )
  FROM baseline_livelihoodzonebaseline lzb,
       baseline_livelihoodstrategy ls
       LEFT JOIN metadata_season s ON s.id = ls.season_id,
       baseline_wealthgroup wg
       LEFT JOIN baseline_community c ON c.id = wg.community_id,
       metadata_wealthgroupcategory wgc
  WHERE lzb.id = la.livelihood_zone_baseline_id
    AND ls.id = la.livelihood_strategy_id
    AND wg.id = la.wealth_group_id
    AND wgc.code = wg.wealth_group_category_code;
"""

CLEAR_SORT_KEY = """
UPDATE baseline_livelihoodactivity SET sort_key = ''
"""


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0033_add_annual_kcals_cost_function"),
        ("metadata", "0016_activitylabel_payment_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="livelihoodactivity",
            name="sort_key",
            field=models.CharField(blank=True, default="", editable=False, max_length=400, verbose_name="Sort Key"),
        ),
        migrations.RunSQL(
            sql=POPULATE_SORT_KEY,
            reverse_sql=CLEAR_SORT_KEY,
        ),
        migrations.AddIndex(
            model_name="livelihoodactivity",
            index=models.Index(fields=["sort_key"], name="activity_sort_key_idx"),
        ),
        migrations.AddIndex(
            model_name="wealthgroup",
            index=models.Index(
                fields=["livelihood_zone_baseline", "wealth_group_category"], name="wg_wealth_category_idx"
            ),
        ),
    ]
