# Generated by Django 5.2.12 on 2026-04-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0033_add_annual_kcals_cost_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelihoodzonebaselinecorrection",
            name="worksheet_name",
            field=models.CharField(
                choices=[
                    ("WB", "WB"),
                    ("Data", "Data"),
                    ("Data2", "Data2"),
                    ("Data3", "Data3"),
                    ("Timeline", "Timeline"),
                    ("Seas Cal", "Seas Cal"),
                ],
                max_length=20,
                verbose_name="Worksheet name",
            ),
        ),
    ]
