# Generated by Django 5.2.13 on 2026-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0035_float_fields_for_fractional_bss_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonalactivity",
            name="is_key",
            field=models.BooleanField(
                default=False,
                help_text="Whether this seasonal activity is a key seasonal activity for the livelihood zone baseline",
                verbose_name="Key Seasonal Activity?",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BaselineSeasonalActivityOccurrence",
            fields=[],
            options={
                "verbose_name": "Baseline Seasonal Activity Occurrence",
                "verbose_name_plural": "Baseline Seasonal Activity Occurrences",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("baseline.seasonalactivityoccurrence",),
        ),
        migrations.AlterField(
            model_name="livelihoodzonebaselinecorrection",
            name="worksheet_name",
            field=models.CharField(
                choices=[
                    ("WB", "WB"),
                    ("Data", "Data"),
                    ("Data2", "Data2"),
                    ("Data3", "Data3"),
                    ("Timeline", "Timeline"),
                    ("Seas Cal", "Seas Cal"),
                ],
                max_length=20,
                verbose_name="Worksheet name",
            ),
        ),
    ]
