# Generated by Django 5.2.12 on 2026-04-24 06:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0038_other_livestock_production"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyParameter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("monitor_quantity", models.BooleanField(default=False, verbose_name="Monitor Quantity")),
                ("monitor_price", models.BooleanField(default=False, verbose_name="Monitor Price")),
                (
                    "livelihood_strategy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_parameter",
                        to="baseline.livelihoodstrategy",
                        verbose_name="Livelihood Strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key Parameter",
                "verbose_name_plural": "Key Parameters",
            },
        ),
        migrations.AlterField(
            model_name="livelihoodzonebaselinecorrection",
            name="worksheet_name",
            field=models.CharField(
                choices=[
                    ("WB", "WB"),
                    ("Data", "Data"),
                    ("Data2", "Data2"),
                    ("Data3", "Data3"),
                    ("Summ", "Summ"),
                    ("Timeline", "Timeline"),
                    ("Seas Cal", "Seas Cal"),
                ],
                max_length=20,
                verbose_name="Worksheet name",
            ),
        ),
    ]
