# Generated by Django 5.2.14 on 2026-07-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0042_rename_main_livelihood_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonalactivityoccurrence",
            name="seasonal_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="baseline.seasonalactivity",
                verbose_name="Seasonal Activity",
            ),
        ),
    ]
