# Generated by Django 5.2.14 on 2026-07-20 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0043_alter_seasonalactivityoccurrence_seasonal_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelihoodproductcategory",
            name="baseline_livelihood_activity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="baseline.baselinelivelihoodactivity",
                verbose_name="Baseline Livelihood Activity",
            ),
        ),
    ]
