# Generated by Django 5.2.16 on 2026-07-30 13:26

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0044_alter_livelihoodproductcategory_baseline_livelihood_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelihoodzonebaselinecorrection",
            name="previous_value",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Previous value before correction",
            ),
        ),
        migrations.AlterField(
            model_name="livelihoodzonebaselinecorrection",
            name="value",
            field=models.JSONField(
                blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name="Corrected value"
            ),
        ),
    ]
