# Generated by Django 5.2.16 on 2026-08-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseline", "0045_alter_livelihoodzonebaselinecorrection_previous_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livelihoodzonebaselinecorrection",
            name="worksheet_name",
            field=models.CharField(
                choices=[
                    ("WB", "WB"),
                    ("Data", "Data"),
                    ("Data2", "Data2"),
                    ("Data3", "Data3"),
                    ("Summ", "Summ"),
                    ("Timeline", "Timeline"),
                    ("Seas Cal", "Seas Cal"),
                    ("Exp factors", "Exp factors"),
                ],
                max_length=20,
                verbose_name="Worksheet name",
            ),
        ),
    ]
