name: Build then test

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

env:
  AWS_REGION: "us-east-1"

jobs:
  lint:
    uses: American-Institutes-for-Research/adw-infra/.github/workflows/run_linters.yml@main
    with:
      check_python: true
      fail_python_format: true
      fail_python_isort: true
      check_secrets: true
      fail_secrets: false
      check_shellscripts: true
      fail_shellscripts: false
      check_safety: false
      fail_safety: false
    secrets: inherit

  test_branch:
    if: ${{ !(startsWith(github.ref, 'refs/tags/')) && !(github.ref == 'refs/heads/main') }}
    needs: [lint]
    uses: ./.github/workflows/run_tests.yml
    with:
      name: test_branch
      test_command: |
        docker compose run \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_REGION \
          -e AWS_DEFAULT_REGION=${AWS_REGION} \
          --name ci-${APP}-${CI_PIPELINE_ID}-${{ github.job }} \
          app --keepdb --exclude-tag=perf 2>&1 | tee test_output.log
      add_version_txt: true
      push_edge_images: true
      push_latest_images: false
      push_tagged_images: false
      aws_role_to_assume: "arn:aws:iam::888016039450:role/data-prod-eks-cluster-github-actions-arc-role"
      ecr_registry: "888016039450.dkr.ecr.us-east-1.amazonaws.com"
      ecr_registry_image: "888016039450.dkr.ecr.us-east-1.amazonaws.com/hea"
      aws_s3_bucket: "fntgithub-ci-artifacts-hea"
    secrets: inherit

  test_keepdb:
    needs: [lint]
    uses: ./.github/workflows/run_tests.yml
    with:
      name: test_keepdb
      test_command: |
        docker compose run --rm \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_REGION \
          -e AWS_DEFAULT_REGION=${AWS_REGION} \
          app --keepdb

        docker compose run \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_REGION \
          -e AWS_DEFAULT_REGION=${AWS_REGION} \
          --name ci-${APP}-${CI_PIPELINE_ID}-${{ github.job }} \
          app --keepdb --exclude-tag=perf 2>&1 | tee test_output.log
      add_version_txt: true
      check_test_output: false
      push_edge_images: true
      push_latest_images: false
      push_tagged_images: false
      aws_role_to_assume: "arn:aws:iam::888016039450:role/data-prod-eks-cluster-github-actions-arc-role"
      ecr_registry: "888016039450.dkr.ecr.us-east-1.amazonaws.com"
      ecr_registry_image: "888016039450.dkr.ecr.us-east-1.amazonaws.com/hea"
      aws_s3_bucket: "fntgithub-ci-artifacts-hea"
    secrets: inherit

  test_main:
    if: github.ref == 'refs/heads/main'
    needs: [lint]
    uses: ./.github/workflows/run_tests.yml
    with:
      name: test_main
      test_command: |
        docker compose run \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_REGION \
          -e AWS_DEFAULT_REGION=${AWS_REGION} \
          -e CHECK_SAFETY=1 \
          -e TEST_OUTPUT_VERBOSE=2 \
          --name ci-${APP}-${CI_PIPELINE_ID}-${{ github.job }} \
          app --keepdb --exclude-tag=perf 2>&1 | tee test_output.log
      add_version_txt: true
      push_edge_images: true
      push_latest_images: true
      push_tagged_images: false
      aws_role_to_assume: "arn:aws:iam::888016039450:role/data-prod-eks-cluster-github-actions-arc-role"
      ecr_registry: "888016039450.dkr.ecr.us-east-1.amazonaws.com"
      ecr_registry_image: "888016039450.dkr.ecr.us-east-1.amazonaws.com/hea"
      aws_s3_bucket: "fntgithub-ci-artifacts-hea"
    secrets: inherit

  test_tag:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [lint]
    uses: ./.github/workflows/run_tests.yml
    with:
      name: test_tag
      test_command: |
        docker compose run \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_REGION \
          -e AWS_DEFAULT_REGION=${AWS_REGION} \
          -e CHECK_SAFETY=1 \
          -e TEST_OUTPUT_VERBOSE=2 \
          --name ci-${APP}-${CI_PIPELINE_ID}-${{ github.job }} \
          app --keepdb --exclude-tag=perf 2>&1 | tee test_output.log
      add_version_txt: false
      force_no_cache_build: true
      push_edge_images: true
      push_latest_images: true
      push_stable_images: true
      push_tagged_images: true
      aws_role_to_assume: "arn:aws:iam::888016039450:role/data-prod-eks-cluster-github-actions-arc-role"
      ecr_registry: "888016039450.dkr.ecr.us-east-1.amazonaws.com"
      ecr_registry_image: "888016039450.dkr.ecr.us-east-1.amazonaws.com/hea"
      aws_s3_bucket: "fntgithub-ci-artifacts-hea"
    secrets: inherit