name: Deploy to environment
run-name: Deploy to ${{ inputs.environment }} triggered by @${{ github.actor }}

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for deployment"
        type: environment
        required: true

env:
  CLIENT: "fnt"
  APP: "hea"
  ENV: ${{ inputs.environment }}
  AWS_REGION: "us-east-1"
  ECS_CLUSTER: "data-prod-ecs-cluster"

jobs:
  deploy_env:
    name: Deploy HEA
    environment: ${{ inputs.environment }}
    runs-on: fewsnet-dind-runners

    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail {0}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: "arn:aws:iam::888016039450:role/data-prod-eks-cluster-github-actions-arc-role"
          aws-region: ${{ env.AWS_REGION }}

      - name: Restart HEA Services
        run: |
          echo "🚀 Deploying $APP to $ENV on ECS cluster: $ECS_CLUSTER"

          SERVICES=(
            "${CLIENT}-${APP}${ENV}-app"
            "${CLIENT}-${APP}${ENV}-dagster-webserver"
            "${CLIENT}-${APP}${ENV}-dagster-daemon"
          )

          for SERVICE in "${SERVICES[@]}"; do
            echo "🔄 Restarting $SERVICE"

            if [[ "$SERVICE" == *"dagster-daemon" ]]; then
              aws ecs update-service \
                --region "$AWS_REGION" \
                --cluster "$ECS_CLUSTER" \
                --service "$SERVICE" \
                --force-new-deployment | jq "del(.[] | .events)"
            else
              aws ecs update-service \
                --region "$AWS_REGION" \
                --cluster "$ECS_CLUSTER" \
                --service "$SERVICE" \
                --force-new-deployment \
                --health-check-grace-period-seconds 600 | jq "del(.[] | .events)"
            fi
          done

          declare -A env_urls=(
            ["dev"]="https://headev.fews.net/en/admin/"
            ["tst"]="https://heastage.fews.net/en/admin/"
          )

          echo "✅ Deployment initiated! Admin URL: ${env_urls[$ENV]:-Unknown environment}"